<a href="https://colab.research.google.com/github/surendra83/aiml-ds-lab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [2]:
X = 2 * np.random.rand(100,1)


In [3]:
X

array([[1.35780369],
       [1.65872894],
       [1.0440983 ],
       [1.59794421],
       [0.72441159],
       [0.00526098],
       [0.14134438],
       [0.42873557],
       [1.38042775],
       [1.82667229],
       [1.88766068],
       [0.69356332],
       [0.69554532],
       [0.80121262],
       [0.39264602],
       [0.19288333],
       [1.59269501],
       [1.87084945],
       [1.04400201],
       [0.81197703],
       [1.37059454],
       [0.03045593],
       [0.02549727],
       [0.01836863],
       [1.45380574],
       [0.72080076],
       [1.19328288],
       [1.25418537],
       [0.06396451],
       [0.8204993 ],
       [1.6215533 ],
       [0.06015975],
       [0.3171518 ],
       [1.63889823],
       [0.95222231],
       [0.90843072],
       [0.82574062],
       [1.74958365],
       [0.6503    ],
       [0.303478  ],
       [1.54677964],
       [1.31419158],
       [1.99857386],
       [1.67389807],
       [0.12405432],
       [0.70504364],
       [1.00552405],
       [1.098

In [4]:
y = 4 + 3 * X + np.random.randn(100,1)

In [5]:
y

array([[ 6.83763863],
       [ 9.31759864],
       [ 7.6281525 ],
       [ 8.09424095],
       [ 5.83961438],
       [ 4.79966158],
       [ 4.18637518],
       [ 3.33385562],
       [ 7.98879908],
       [ 8.33485138],
       [10.56558431],
       [ 4.81363923],
       [ 5.53069633],
       [ 5.90435848],
       [ 4.45557768],
       [ 4.00867282],
       [10.26030061],
       [10.67519471],
       [ 6.34820273],
       [ 5.0748562 ],
       [ 7.40266551],
       [ 4.02710215],
       [ 3.53803637],
       [ 3.30893242],
       [ 8.72713708],
       [ 6.52441017],
       [ 7.90350001],
       [ 7.59058588],
       [ 4.60829923],
       [ 4.61637222],
       [ 8.85128388],
       [ 4.58535093],
       [ 4.97447455],
       [ 9.71922037],
       [ 6.33683363],
       [ 5.61709691],
       [ 7.70051698],
       [ 8.2366592 ],
       [ 5.61916782],
       [ 5.06294578],
       [ 8.35041329],
       [ 6.91813669],
       [10.95171766],
       [10.28307732],
       [ 6.22627943],
       [ 6

In [6]:
data = pd.DataFrame(data = np.hstack((X,y)), columns = ['X','y'])

In [7]:
data

X          y
0   1.357804   6.837639
1   1.658729   9.317599
2   1.044098   7.628152
3   1.597944   8.094241
4   0.724412   5.839614
..       ...        ...
95  0.795747   7.837912
96  1.841191   9.909068
97  1.054751   7.437399
98  1.925089  11.352524
99  1.143276   7.130085

[100 rows x 2 columns]

In [8]:
#data seperation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 1), (20, 1), (80, 1), (20, 1))

In [10]:
# Regratition
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = model.predict(X_test)

In [12]:
y_pred


array([[5.55407286],
       [8.58293345],
       [4.21802718],
       [5.94858464],
       [4.14866438],
       [4.70452368],
       [3.843332  ],
       [8.15272697],
       [9.61236353],
       [7.97085255],
       [6.99868665],
       [8.78795582],
       [6.17794367],
       [8.84169087],
       [5.57441188],
       [6.00858706],
       [7.6921436 ],
       [4.53704583],
       [5.91915861],
       [3.95071729]])

In [13]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')


Mean Squared Error: 0.935292976806878
R-squared: 0.7829775098307549
